// Catálogo real de MAVIA — 52 referencias. ing[] enlaza con la base de ingredientes
// para que el semáforo del cliente se calcule solo. x[] son avisos propios del producto.
window.PROD = [

/* ─── NUTRALIE ─────────────────────────────────────────────── */
{id:"nut-biotin",n:"Biotin Complex",m:"Nutralie",f:"120 cápsulas · 1 al día",pvp:20.90,ean:"8436590431016",img:"nut-biotin",
 u:"Pelo, piel y uñas",
 comp:"Biotina 10.000 µg · Vitamina E 25 mg · Zinc 15 mg · Selenio 55 µg · Vitamina D 50 µg",
 ing:["vit-b7","vit-e","zinc","selenio","vit-d"],
 x:[{k:"analitica",l:"R",t:"10.000 µg de biotina es una dosis muy alta: FALSEA las analíticas de tiroides y de troponina. Di siempre que hay que dejarlo 3 días antes de cualquier análisis de sangre. Es el aviso más importante de este producto."}]},

{id:"nut-colageno-marino",n:"Marine Collagen Complex",m:"Nutralie",f:"60 cápsulas · 1-2 al día",pvp:23.50,ean:"8436590431290",img:"nut-colageno-marino",
 u:"Piel, elasticidad, hidratación, antioxidante",
 comp:"Colágeno marino hidrolizado 500 mg · Ácido hialurónico 22,5 mg · Vitamina C 12,5 mg · Q10 7,5 mg · Licopeno 3,75 mg · Vitamina E · Zinc · B12 (por cápsula)",
 ing:["colageno","hialuronico","vit-c","cq10","licopeno","vit-e","zinc","vit-b12"],
 x:[{k:"alergia_pescado",l:"R",t:"El colágeno es MARINO. Contraindicado en alergia a pescado. Si te piden colágeno y son alérgicos, hay que buscar otro origen."}]},

{id:"nut-resveratrol-nad",n:"Trans Resveratrol & NAD+ Complex",m:"Nutralie",f:"60 cápsulas · 1-2 al día",pvp:34.90,ean:"8436590431498",img:"nut-resveratrol-nad",
 u:"Antiedad, longevidad, antioxidante",
 comp:"Resveratrol 500 mg · NAD+ 60 mg · Quercetina 50 mg · Proantocianidinas de uva 46,5 mg · Vitamina C 40 mg · Piperina 4,75 mg (por cápsula)",
 ing:["resveratrol","quercetina","opc-uva","nmn","vit-c"],
 x:[{k:"_destacado",l:"A",t:"Lleva NAD+. El estatus de los precursores de NAD como nuevo alimento en la UE sigue sin cerrarse: pide a tu proveedor por escrito la documentación de que esta referencia está notificada en España."},
    {k:"medicacion_general",l:"A",t:"La piperina multiplica la absorción de muchos fármacos. Con medicación crónica, separa 2 horas y consulta."}]},

{id:"nut-omega3",n:"Omega 3 Complex",m:"Nutralie",f:"60 perlas · 2 al día",pvp:19.90,ean:"8436590431030",img:"nut-omega3",
 u:"Corazón, visión, rendimiento cerebral",
 comp:"Aceite de pescado 1.963 mg · EPA 903 mg · DHA 353 mg · Vitamina E 24 mg · Vitamina D 10 µg (por 2 perlas)",
 ing:["omega3","vit-e","vit-d"],
 x:[{k:"anticoag",l:"R",t:"1.256 mg de EPA+DHA al día es dosis alta. Con Sintrom o antiagregantes, no lo vendas sin que lo apruebe su médico."}]},

{id:"nut-red-yeast",n:"Red Yeast Rice Complex",m:"Nutralie",f:"90 cápsulas · 1 al día",pvp:24.90,ean:"8436590431337",img:"nut-red-yeast",
 u:"Colesterol y salud cardiovascular",
 comp:"Monacolina K 2,54 mg · Salvia 150 mg · Esteroles vegetales 100 mg · Ajo 100 mg · Vitamina C 80 mg · Q10 30 mg · Policosanol 19,6 mg · Niacina 16 mg",
 ing:["levadura-roja","cq10","policosanol","fitoesteroles","ajo","salvia","vit-c","vit-b3","vit-e","vit-b5"],
 x:[{k:"_destacado",l:"R",t:"★ PRODUCTO DE FARMACIA DISFRAZADO DE COMPLEMENTO. La monacolina K es lovastatina. 2,54 mg/cápsula cumple el límite legal (menos de 3 mg), pero tiene los mismos riesgos que una estatina. Trátalo como un medicamento: nunca a quien ya tome estatinas, ni en embarazo, ni en menores de 18, ni con problemas de hígado."},
    {k:"muscular",l:"A",t:"Si el cliente vuelve con dolor muscular intenso, debilidad u orina oscura: que lo suspenda y vaya a urgencias."}]},

{id:"nut-curcuma",n:"Turmeric Curcuma Complex",m:"Nutralie",f:"120 cápsulas · 2 al día",pvp:19.90,ean:"8436590431078",img:"nut-curcuma",
 u:"Antioxidante, antiinflamatorio, digestivo",
 comp:"Cúrcuma 1.300 mg · Jengibre 100 mg · Pimienta negra 20 mg (por 2 cápsulas)",
 ing:["curcuma","jengibre"],
 x:[{k:"anticoag",l:"R",t:"Cúrcuma 1.300 mg + jengibre + pimienta negra que multiplica la absorción: efecto antiagregante real. No con Sintrom ni aspirina."},
    {k:"medicacion_general",l:"A",t:"La pimienta negra aumenta la absorción de otros fármacos. Separar 2 horas de la medicación."}]},

{id:"nut-men",n:"Men Complex",m:"Nutralie",f:"90 cápsulas · 3 al día",pvp:24.90,ean:"8436590431306",img:"nut-men",
 u:"Vitalidad masculina, energía, rendimiento",
 comp:"L-Arginina 1.000 mg · Maca 500 mg · Ginseng coreano 100 mg · Ginkgo biloba 90 mg · Tríbulus 37,5 mg · Zinc 6,45 mg · Selenio 45 µg (por 3 cápsulas)",
 ing:["arginina","maca","ginseng","ginkgo","tribulus","zinc","selenio"],
 x:[{k:"_destacado",l:"R",t:"Lleva ginkgo + ginseng + arginina: tres cosas que afectan a la coagulación y a la tensión. Es un producto que parece inocente y no lo es."},
    {k:"prostata",l:"R",t:"El tríbulus puede empeorar la hiperplasia de próstata y está desaconsejado en cáncer de próstata. Pregúntalo antes de venderlo a un hombre mayor de 50."}]},

{id:"nut-women",n:"Women Complex",m:"Nutralie",f:"90 cápsulas · 3 al día",pvp:24.90,ean:"8436590431375",img:"nut-women",
 u:"Equilibrio hormonal, energía, libido, huesos",
 comp:"Calcio 203 mg · Maca 200 mg · Angélica china 100 mg · L-cisteína 100 mg · Magnesio 100 mg · Ginkgo 50 mg · Azafrán 30 mg · Sauzgatillo 20 mg · Q10 20 mg · Hierro 14 mg · Vitamina A 800 µg · Folato 300 µg · Vitamina K 40 µg · y 20 nutrientes más",
 ing:["agnocasto","dong-quai","maca","ginkgo","azafran","tribulus","cq10","hierro","calcio","magnesio","vit-a","vit-b6","folato","vit-k","vit-d","inositol","cromo","selenio","cobre","manganeso","molibdeno","silicio","colina","vit-c","vit-b12","vit-b3","vit-b5","vit-b7","tirosina"],
 x:[{k:"_destacado",l:"R",t:"★ EL PRODUCTO MÁS COMPLICADO DE TU LINEAL. Lleva sauzgatillo (hormonal), angélica china (anticoagulante), ginkgo (anticoagulante), azafrán (serotoninérgico), vitamina A y vitamina K. Pregunta SIEMPRE por medicación, embarazo y antecedentes de tumor hormonal antes de venderlo."},
    {k:"hormonal",l:"R",t:"El sauzgatillo puede restar eficacia a los anticonceptivos y descontrolar una terapia hormonal. No vender sin consultar."}]},

{id:"nut-ashwagandha",n:"Ashwagandha Complex",m:"Nutralie",f:"60 cápsulas · 1 al día",pvp:24.90,ean:"8436590431238",img:"nut-ashwagandha",
 u:"Estrés, sistema nervioso, rendimiento mental",
 comp:"Ashwagandha KSM-66 550 mg (withanólidos 27,5 mg) · Rhodiola 60 mg · Vitamina B6 0,8 mg · B12 1,3 µg",
 ing:["ashwagandha","rhodiola","vit-b6","vit-b12"],
 x:[{k:"tiroidec",l:"R",t:"550 mg de KSM-66 es dosis alta. La ashwagandha sube la T4: en cualquier problema de tiroides, no lo vendas sin endocrino."}]},

{id:"nut-detox",n:"Detox Complex",m:"Nutralie",f:"90 cápsulas · 3 al día",pvp:24.90,ean:"8436590431146",img:"nut-detox",
 u:"Depurativo, retención de líquidos, hígado",
 comp:"Alcachofa 675 mg · Rábano negro 375 mg · Grosellero negro 210 mg · Diente de león 105 mg · Escaramujo 90 mg · Cardo mariano 90 mg · Castaño de Indias 60 mg · Ortiga 60 mg · Hinojo 60 mg · Papaya 60 mg · Colina 30 mg",
 ing:["alcachofa","rabano-negro","grosellero","diente-leon","acerola","cardo-mariano","castano-indias","ortiga","hinojo","colina","vit-b6","vit-b1"],
 x:[{k:"biliar",l:"R",t:"Alcachofa + rábano negro + diente de león: tres coleréticos juntos. En cálculos de vesícula puede provocar un cólico. Pregunta siempre por la vesícula antes de vender un depurativo."},
    {k:"anticoag",l:"R",t:"El castaño de Indias y la ortiga interfieren con el Sintrom en sentidos opuestos. No vender con anticoagulantes."}]},

{id:"nut-garcinia",n:"Garcinia Cambogia Complex",m:"Nutralie",f:"90 cápsulas · 3 al día",pvp:20.90,ean:"8436590431047",img:"nut-garcinia",
 u:"Control de peso, saciedad, metabolismo",
 comp:"Garcinia Cambogia 2.000 mg (60% HCA = 1.200 mg) · Zinc 15 mg · Vitamina B2 4,2 mg · Vitamina B6 4,2 mg · Cromo 60 µg (por 3 cápsulas)",
 ing:["garcinia","zinc","vit-b2","vit-b6","cromo"],
 x:[{k:"hepatica",l:"R",t:"2.000 mg de garcinia al día es dosis alta y hay casos documentados de hepatotoxicidad grave. No lo vendas a nadie con el hígado tocado ni junto a otros productos hepatotóxicos."},
    {k:"antidep",l:"R",t:"La garcinia es serotoninérgica: con ISRS hay riesgo de síndrome serotoninérgico. No vender."}]},

{id:"nut-biprotics",n:"Biprotics 30 Strains Complex",m:"Nutralie",f:"60 cápsulas · 2-4 al día",pvp:29.90,ean:"8436590431276",img:"nut-biprotics",
 u:"Flora intestinal, defensas, flora íntima",
 comp:"Mix de 30 cepas 132.000 millones UFC · Inulina 200 mg · Zinc 5 mg · Vitamina D3 5 µg (por 2 cápsulas)",
 ing:["probioticos","prebioticos","zinc","vit-d"],
 x:[{k:"digestivo",l:"A",t:"132.000 millones de UFC es una dosis muy alta y lleva inulina (FODMAP). En colon irritable o SIBO puede dar bastantes gases los primeros días. Empezar por 1 cápsula."}]},

{id:"nut-maca-negra",n:"Black Maca Complex",m:"Nutralie",f:"120 cápsulas · 3-4 al día",pvp:21.90,ean:"8436590431009",img:"nut-maca-negra",
 u:"Energía, vigor, fertilidad, testosterona",
 comp:"Extracto de maca negra 1.600 mg (equiv. 24.000 mg planta) · L-Arginina 600 mg · Zinc 15 mg · Vitamina B6 5,6 mg · B12 10 µg (por 4 cápsulas)",
 ing:["maca","arginina","zinc","vit-b6","vit-b12"],
 x:[{k:"herpes",l:"A",t:"600 mg de arginina pueden reactivar el herpes labial en personas propensas. Si el cliente los tiene a menudo, avísale."}]},

{id:"nut-b-complex",n:"Vitamin B Complex",m:"Nutralie",f:"90 cápsulas · 1 al día",pvp:20.90,ean:"8436590431382",img:"nut-b-complex",
 u:"Energía, sistema nervioso, estrés",
 comp:"B3 54 mg · Vitamina C 80 mg · Inositol 75 mg · Colina 75 mg · PABA 75 mg · B2 25 mg · B1 25 mg · B5 18 mg · B6 10 mg · Folato 400 µg · B12 75 µg · Biotina 75 µg",
 ing:["vit-b3","vit-b2","vit-b1","vit-c","inositol","colina","paba","vit-b5","vit-b6","folato","vit-b7","vit-b12"],
 x:[{k:"_destacado",l:"R",t:"★ OJO CON SUMAR. Lleva 10 mg de vitamina B6 y el límite de la EFSA son 12 mg/día. Si el cliente se lleva también el Women Complex (2,1 mg) o la Garcinia (4,2 mg), SE PASA del límite y el exceso de B6 causa neuropatía. No vendas dos productos con B6 a la misma persona sin sumar."},
    {k:"analitica",l:"A",t:"Lleva 75 µg de biotina: puede alterar analíticas de tiroides. Suspender 3 días antes."}]},

{id:"nut-q10",n:"Q10 200 mg Complex",m:"Nutralie",f:"120 cápsulas · 1 al día",pvp:29.90,ean:"8436590431481",img:"nut-q10",
 u:"Energía, antioxidante, acompañante de estatinas",
 comp:"Coenzima Q10 200 mg · Vitamina C 40 mg · Vitamina E 10 mg · Pimienta negra 5 mg · B2 1,4 mg",
 ing:["cq10","vit-c","vit-e","vit-b2"],
 x:[{k:"estatinas",l:"V",t:"Venta muy razonable: las estatinas reducen la CoQ10 del organismo. Aquí el Q10 juega a favor, no en contra."}]},

{id:"nut-glucosamina",n:"Glucosamine Complex",m:"Nutralie",f:"120 comprimidos · 2 al día",pvp:23.90,ean:"8436590431191",img:"nut-glucosamina",
 u:"Articulaciones, movilidad, cartílago",
 comp:"Glucosamina 1.000 mg · Condroitina 500 mg · MSM 450 mg · Boswellia 200 mg · Colágeno 80 mg · Ácido hialurónico 30 mg · Zinc 8 mg · Selenio 30 µg",
 ing:["glucosamina","condroitina","msm","boswellia","colageno","hialuronico","zinc","selenio"],
 x:[{k:"alergia_marisco",l:"R",t:"La glucosamina se obtiene de caparazón de crustáceos. Pregunta SIEMPRE por la alergia al marisco antes de vender cualquier producto de articulaciones."},
    {k:"anticoag",l:"R",t:"Glucosamina + condroitina + boswellia: tres que tocan la coagulación. Hay casos de INR disparado con Sintrom."}]},

{id:"nut-magnesio",n:"Magnesium Complex",m:"Nutralie",f:"120 cápsulas · 2-3 al día",pvp:19.90,ean:"8436590431054",img:"nut-magnesio",
 u:"Energía, músculos, calambres, recuperación",
 comp:"Citrato de magnesio 1.545 mg + bisglicinato 600 mg = 302 mg de magnesio elemento · Vitamina C 120 mg · B5 9 mg · B6 2,1 mg (por 3 cápsulas)",
 ing:["magnesio","vit-c","vit-b5","vit-b6"],
 x:[{k:"renal",l:"R",t:"302 mg de magnesio al día es dosis plena. En insuficiencia renal el magnesio se acumula y es peligroso: pregunta por el riñón en clientes mayores."}]},

{id:"nut-d3k2",n:"Vitamin D3 + K2 Complex",m:"Nutralie",f:"60 perlas · 1 cada 10 días",pvp:20.90,ean:"8436590431139",img:"nut-d3k2",
 u:"Huesos, músculos, defensas",
 comp:"Vitamina D 250 µg (10.000 UI) y Vitamina K2 MK-7 100 µg por perla · Extracto de bambú · Silicio · Vitamina C",
 ing:["vit-d","vit-k","silicio","vit-c"],
 x:[{k:"_destacado",l:"R",t:"★ POSOLOGÍA RARA Y PELIGROSA SI SE EXPLICA MAL. Cada perla lleva 10.000 UI, pensada para UNA CADA 10 DÍAS. Si el cliente la toma a diario está tomando 10 veces el límite. Escríbeselo en la caja delante de él."},
    {k:"anticoag",l:"R",t:"100 µg de vitamina K2 antagonizan el Sintrom. NO VENDER a nadie con acenocumarol."}]},

{id:"nut-triple-magnesio",n:"Triple Magnesio",m:"Nutralie",f:"120 cápsulas",pvp:27.90,ean:"",img:"",
 u:"Calambres, descanso, energía",
 comp:"Referencia que no aparece en el catálogo 2025 que me pasaste — composición sin confirmar.",
 ing:["magnesio"],
 pend:true,
 x:[{k:"_destacado",l:"A",t:"No he podido confirmar la composición: esta referencia no está en el catálogo Nutralie 2025. Pásame la etiqueta o el enlace y completo la ficha. Mientras tanto trátalo como un magnesio normal."},
    {k:"renal",l:"R",t:"Como todo magnesio: contraindicado en insuficiencia renal."}]},

/* ─── FEPADIET ─────────────────────────────────────────────── */
{id:"fepa-astaxantina",n:"Astaxantina liposomada",m:"Fepa",f:"60 cápsulas",pvp:29.30,ean:"",img:"fepa-krill",
 u:"Antioxidante, piel, sol, deporte, vista",
 comp:"Astaxantina liposomada. En el catálogo de Fepa la astaxantina aparece asociada al aceite de krill.",
 ing:["astaxantina"],
 x:[{k:"alergia_marisco",l:"R",t:"CONFIRMA EL ORIGEN en la etiqueta. Si la astaxantina viene de krill, es crustáceo y está contraindicada en alergia al marisco. Si viene de la microalga Haematococcus, no hay problema."},
    {k:"anticoag",l:"A",t:"Efecto antiagregante leve. Prudencia con Sintrom."}]},

{id:"fepa-berberina",n:"Berberina 750 mg",m:"Fepa",f:"60 cápsulas",pvp:29.95,ean:"",img:"fepa-berberina",
 u:"Glucemia, colesterol, síndrome metabólico",
 comp:"Extracto seco de Berberis vulgaris (raíz) 750 mg",
 ing:["berberina"],
 x:[{k:"_destacado",l:"R",t:"★ 750 mg es dosis alta. La berberina se comporta como un fármaco: inhibe el CYP3A4 y multiplica los niveles de mucha medicación. Si el cliente toma cualquier pastilla a diario, deriva al farmacéutico antes de vender."},
    {k:"antidiab",l:"R",t:"Baja la glucemia de verdad. Sumada a metformina o insulina puede provocar una hipoglucemia."}]},

{id:"fepa-boswelia",n:"Boswelia",m:"Fepa",f:"60 cápsulas",pvp:19.95,ean:"",img:"",
 u:"Articulaciones, inflamación",
 comp:"Extracto de Boswellia serrata. Composición exacta sin confirmar (no está en el catálogo que me pasaste).",
 ing:["boswellia"],pend:true,
 x:[{k:"_destacado",l:"A",t:"Ficha basada en el nombre del producto. Pásame la etiqueta y confirmo la dosis de ácidos boswélicos."}]},

{id:"fepa-curcuma",n:"Cúrcuma liposomada",m:"Fepa",f:"60 cápsulas",pvp:31.40,ean:"",img:"fepa-curcuma",
 u:"Articulaciones, inflamación, digestión",
 comp:"Cúrcuma liposomada estandarizada >95% 450 mg = 427,5 mg de curcuminoides por cápsula",
 ing:["curcuma"],
 x:[{k:"_destacado",l:"R",t:"427 mg de curcuminoides puros en forma liposomada: esto se absorbe muchísimo más que una cúrcuma normal. Todas las precauciones de la cúrcuma cuentan doble aquí, sobre todo la del hígado y la de la vesícula."},
    {k:"hepatica",l:"R",t:"Las formas de alta biodisponibilidad son justo las implicadas en los casos de hepatitis tóxica por cúrcuma. No vender con el hígado tocado."}]},

{id:"fepa-ester-c",n:"Ester C liposomada",m:"Fepa",f:"60 cápsulas",pvp:20.95,ean:"",img:"fepa-ester-c",
 u:"Defensas, antioxidante, colágeno, absorción de hierro",
 comp:"Ascorbato de calcio 800 mg (vitamina C) · hesperidina de Citrus sinensis · rutina · liposoma de girasol",
 ing:["vit-c","calcio"],
 x:[{k:"renal",l:"R",t:"800 mg de vitamina C más el calcio del ascorbato: en litiasis renal por oxalato cálcico, no."},
    {k:"hemocromatosis",l:"R",t:"Aumenta mucho la absorción de hierro. Contraindicada en hemocromatosis."}]},

{id:"fepa-glutation",n:"Glutathion R Liposomado",m:"Fepa",f:"60 cápsulas",pvp:38.00,ean:"",img:"fepa-glutation",
 u:"Antioxidante, hígado, piel, detoxificación",
 comp:"Glutatión reducido · Vitamina C (ascorbato cálcico 82%) · Liposoma de fosfatidilcolina de girasol · Aceite de oliva",
 ing:["glutation","vit-c"],
 x:[{k:"quimio",l:"A",t:"Es el antioxidante más potente del organismo. Durante quimio o radioterapia tiene que autorizarlo el oncólogo."}]},

{id:"fepa-nac",n:"NAC Forte",m:"Fepa",f:"60 cápsulas",pvp:23.00,ean:"",img:"fepa-nac",
 u:"Antioxidante, mucolítico, hígado, respiratorio",
 comp:"N-Acetil L-Cisteína",
 ing:["nac"],
 x:[{k:"_destacado",l:"A",t:"En España la acetilcisteína también existe como medicamento. Si el cliente la quiere para una tos o mucosidad concretas, puede salirle mejor y más barato en farmacia."}]},

{id:"fepa-omega3",n:"Omega 3 Forte",m:"Fepa",f:"60 cápsulas",pvp:26.95,ean:"",img:"fepa-omega3",
 u:"Corazón, triglicéridos, inflamación",
 comp:"Aceite de pescado de alta concentración en EPA y DHA",
 ing:["omega3"],
 x:[{k:"anticoag",l:"A",t:"Al ser 'forte', la dosis de EPA+DHA es alta. Con anticoagulantes, máximo 1 g/día y que lo sepa su médico."}]},

{id:"fepa-oregano",n:"Orégano Forte (perlas)",m:"Fepa",f:"60 perlas",pvp:26.20,ean:"",img:"fepa-oregano",
 u:"Defensas, antimicrobiano intestinal, candidiasis",
 comp:"Aceite de oliva virgen extra · Aceite esencial de orégano · Perla de gelatina bovina de liberación lenta",
 ing:["oregano-ae"],
 x:[{k:"religioso",l:"R",t:"La perla es de GELATINA BOVINA. No apto para veganos ni vegetarianos. Relevante también para clientes halal si no está certificada."},
    {k:"digestivo",l:"R",t:"Aceite esencial concentrado: muy irritante para el estómago. Siempre con comida y nunca en úlcera o gastritis."}]},

{id:"fepa-peptasa",n:"Peptasa 130.000",m:"Fepa",f:"60 cápsulas",pvp:39.95,ean:"",img:"fepa-peptasa",
 u:"Inflamación, articulaciones, recuperación deportiva",
 comp:"Serrazimes® — proteasas de Aspergillus melleus y Aspergillus oryzae, 130.000 U/g",
 ing:["proteasas"],
 x:[{k:"_destacado",l:"R",t:"★ Son enzimas fibrinolíticas a dosis alta. Se toman EN AYUNAS para que actúen como antiinflamatorio (con comida solo hacen digestión). Ese mismo efecto es el que las hace peligrosas con anticoagulantes y antes de una cirugía."}]},

{id:"fepa-probiotic",n:"Probiotic",m:"Fepa",f:"40 cápsulas",pvp:35.00,ean:"",img:"fepa-probiotic",
 u:"Flora intestinal, tras antibióticos, defensas",
 comp:"Probióticos de alta concentración (50.000 millones UFC por cápsula según catálogo)",
 ing:["probioticos"],
 x:[{k:"antibiot",l:"A",t:"Si es para acompañar un antibiótico, separar 2-3 horas de la toma del antibiótico."}]},

{id:"fepa-prostal",n:"Prostal",m:"Fepa",f:"30 cápsulas",pvp:21.95,ean:"",img:"fepa-prostal",
 u:"Próstata, hiperplasia benigna, vías urinarias",
 comp:"Sabal (Serenoa repens) 200 mg equiv. 1.000 mg planta · Pygeum africanum 200 mg equiv. 1.000 mg planta · Ácido L-glutámico 200 mg",
 ing:["sabal","pygeum"],
 x:[{k:"prostata",l:"R",t:"★ EL AVISO CLAVE: el sabal BAJA EL PSA y puede enmascarar un cáncer de próstata. Nunca lo vendas sin que el urólogo haya descartado el cáncer, y dile que avise antes de hacerse un PSA."}]},

{id:"fepa-psicobiotic",n:"Psicobiotic",m:"Fepa",f:"30 cápsulas",pvp:22.50,ean:"",img:"",
 u:"Eje intestino-cerebro, ánimo, estrés",
 comp:"Cepas probióticas psicobióticas. Composición exacta sin confirmar.",
 ing:["probioticos"],pend:true,
 x:[{k:"_destacado",l:"A",t:"Ficha provisional: no está en el catálogo que me pasaste. Necesito la etiqueta, sobre todo para ver si lleva algún aminoácido serotoninérgico añadido, que cambiaría el semáforo con antidepresivos."}]},

{id:"fepa-teanina",n:"Teanina",m:"Fepa",f:"60 cápsulas",pvp:15.70,ean:"",img:"",
 u:"Calma sin sedación, foco, descanso",
 comp:"L-Teanina. ATENCIÓN: Fepa tiene también una fórmula de descanso con amapola de California, GABA, L-teanina y Griffonia.",
 ing:["teanina"],pend:true,
 x:[{k:"_destacado",l:"R",t:"★ COMPRUEBA LA ETIQUETA ANTES DE VENDERLO. Si esta referencia es L-teanina sola, es de lo más seguro que tienes. Si es la fórmula combinada que lleva GRIFFONIA (5-HTP), entonces está CONTRAINDICADA con cualquier antidepresivo por riesgo de síndrome serotoninérgico. Es una diferencia enorme: mírala y dime cuál es."},
    {k:"antidep",l:"R",t:"Mientras no confirmes la etiqueta, no lo vendas a nadie que tome antidepresivos."}]},

/* ─── KLAU · MIEL DE MANUKA ─────────────────────────────────── */
{id:"klau-261",n:"Manuka Honey MGO 261+",m:"KLAU",f:"250 g",pvp:26.95,ean:"",img:"",
 u:"Prevención diaria, defensas, garganta, microbiota",
 comp:"Miel de Manuka con 261 mg/kg de metilglioxal",
 ing:["manuka"],
 x:[{k:"_destacado",l:"V",t:"Es el nivel de entrada de la gama: mantenimiento y prevención. Para síntomas ya instalados, el 512+."}]},

{id:"klau-261-resv",n:"Manuka MGO 261+ con Resveratrol",m:"KLAU",f:"250 g",pvp:31.93,ean:"",img:"",
 u:"Defensas, antioxidante, circulación",
 comp:"Miel de Manuka 261+ con resveratrol añadido",
 ing:["manuka","resveratrol"],
 x:[{k:"anticoag",l:"R",t:"El resveratrol añadido tiene efecto antiagregante. Esta versión, a diferencia de la Manuka sola, no se la vendas a nadie con Sintrom o aspirina."},
    {k:"hormonodep",l:"R",t:"El resveratrol es fitoestrógeno: evitar en tumores hormonodependientes."}]},

{id:"klau-512",n:"Manuka Honey MGO 512+",m:"KLAU",f:"250 g",pvp:48.35,ean:"",img:"",
 u:"Síntomas leves o moderados: garganta, aftas, encías, reflujo",
 comp:"Miel de Manuka con 512 mg/kg de metilglioxal",
 ing:["manuka"],x:[]},

{id:"klau-826",n:"Manuka Honey MGO 826+",m:"KLAU",f:"250 g",pvp:65.36,ean:"",img:"",
 u:"Tratamiento intensivo: infecciones activas, sinusitis",
 comp:"Miel de Manuka con 826 mg/kg de metilglioxal",
 ing:["manuka"],
 x:[{k:"_destacado",l:"A",t:"Es el más caro de la gama y el que más te van a pedir por recomendación. Ojo con el lenguaje: puedes hablar de uso tradicional, pero no puedes decir que trata ni cura una infección."}]},

/* ─── VOLCÁN · ACEITES DE CBD ───────────────────────────────── */
{id:"volcan-5",n:"Volcán CBD 5%",m:"Volcán",f:"10 ml",pvp:19.90,ean:"",img:"",u:"Aceite de CBD de cultivo ecológico de Tenerife",comp:"5% de cannabidiol · extracción CO2 de flores",ing:["cbd"],x:[]},
{id:"volcan-10",n:"Volcán CBD 10%",m:"Volcán",f:"10 ml",pvp:31.25,ean:"",img:"",u:"Aceite de CBD",comp:"10% de cannabidiol",ing:["cbd"],x:[]},
{id:"volcan-15",n:"Volcán CBD 15%",m:"Volcán",f:"10 ml",pvp:37.65,ean:"",img:"",u:"Aceite de CBD",comp:"15% de cannabidiol",ing:["cbd"],x:[]},
{id:"volcan-20",n:"Volcán CBD 20%",m:"Volcán",f:"10 ml",pvp:44.50,ean:"",img:"",u:"Aceite de CBD",comp:"20% de cannabidiol",ing:["cbd"],x:[]},
{id:"volcan-30",n:"Volcán CBD 30%",m:"Volcán",f:"10 ml",pvp:57.00,ean:"",img:"",u:"Aceite de CBD",comp:"30% de cannabidiol",ing:["cbd"],x:[]},
{id:"volcan-40",n:"Volcán CBD 40%",m:"Volcán",f:"10 ml",pvp:67.20,ean:"",img:"",u:"Aceite de CBD",comp:"40% de cannabidiol",ing:["cbd"],x:[]},
{id:"volcan-50",n:"Volcán CBD 50%",m:"Volcán",f:"10 ml",pvp:88.00,ean:"",img:"",u:"Aceite de CBD",comp:"50% de cannabidiol — una de las concentraciones más altas del mercado",ing:["cbd"],x:[]},
{id:"volcan-cbn",n:"Volcán CBN + Melatonina",m:"Volcán",f:"10 ml",pvp:36.50,ean:"",img:"",
 u:"Descanso nocturno",comp:"CBN (cannabinol) con melatonina",ing:["cbn","melatonina"],
 x:[{k:"conduccion",l:"R",t:"CBN y melatonina juntos: sedación importante. No conducir. Dilo siempre."}]},

/* ─── FISIOMAX · USO EXTERNO ────────────────────────────────── */
{id:"fisio-cbd-crema",n:"Fisiomax CBD crema",m:"Fisiomax",f:"75 ml · uso externo",pvp:16.95,ean:"8437028983008",img:"",top:true,
 u:"Contracturas, dolor muscular y articular",comp:"Crema de masaje con CBD",ing:[],
 x:[{k:"_destacado",l:"V",t:"CBD DE USO TÓPICO: este sí es legal en España sin problemas, a diferencia de los aceites de tomar. Véndelo con tranquilidad."},
    {k:"herida",l:"R",t:"No aplicar sobre heridas abiertas ni piel irritada."}]},
{id:"fisio-cbd-roll",n:"Fisiomax CBD Roll On",m:"Fisiomax",f:"75 ml · uso externo",pvp:15.50,ean:"8437028983039",img:"",top:true,
 u:"Aplicación localizada en contracturas",comp:"Roll-on con CBD",ing:[],
 x:[{k:"_destacado",l:"V",t:"CBD tópico: legal y sin las complicaciones del aceite oral."}]},
{id:"fisio-calor-crema",n:"Fisiomax Crema de Calor + CBD",m:"Fisiomax",f:"75 ml · uso externo",pvp:15.50,ean:"8437028983084",img:"",top:true,
 u:"Efecto calor para contracturas y dolor muscular",comp:"Crema de calor con CBD",ing:["capsaicina"],x:[]},
{id:"fisio-calor-roll",n:"Fisiomax Roll On de Calor + CBD",m:"Fisiomax",f:"75 ml · uso externo",pvp:13.50,ean:"8437028983114",img:"",top:true,
 u:"Efecto calor localizado",comp:"Roll-on de calor con CBD",ing:["capsaicina"],x:[]},
{id:"fisio-f12-crema",n:"Fisiomax F12 crema de masaje",m:"Fisiomax",f:"75 ml · uso externo",pvp:11.10,ean:"8437028983046",img:"",top:true,
 u:"Masaje deportivo, efecto frío",comp:"Crema de masaje F12",ing:["mentol-alcanfor"],x:[]},
{id:"fisio-f12-roll",n:"Fisiomax F12 Roll On",m:"Fisiomax",f:"75 ml · uso externo",pvp:10.95,ean:"8437028983077",img:"",top:true,
 u:"Masaje localizado, efecto frío",comp:"Roll-on F12",ing:["mentol-alcanfor"],x:[]},
{id:"fisio-balsamo",n:"Fisiomax Bálsamo Tigre + CBD",m:"Fisiomax",f:"30 g · uso externo",pvp:15.95,ean:"",img:"",top:true,
 u:"Contracturas, cuello, espalda",comp:"Bálsamo tipo tigre con CBD",ing:["mentol-alcanfor","capsaicina"],
 x:[{k:"menor",l:"R",t:"Los bálsamos tipo tigre llevan alcanfor y mentol: no aplicar en la cara ni en el pecho de niños pequeños."}]}

];
